"""`git` replacement placed first on an agent's PATH during a run.

Checks every invocation with command_guard.check_git and, when allowed, execs
the real git. Configuration comes from the environment the controller sets:
AUTOBUILD_REAL_GIT and AUTOBUILD_WORKTREE.
"""

import os
import sys
from pathlib import Path

from autobuild.git.command_guard import check_git

SHIM_SCRIPT = """#!/bin/sh
# Generated by autobuild for one run: routes agent git calls through the guard.
PYTHONPATH="{core}${{PYTHONPATH:+:$PYTHONPATH}}" exec "{python}" -m autobuild.git.git_shim "$@"
"""


def write_shim(bin_directory: Path, python: str, core: Path) -> Path:
    """Create `<bin_directory>/git` and return it."""
    bin_directory.mkdir(parents=True, exist_ok=True)
    shim = bin_directory / "git"
    shim.write_text(SHIM_SCRIPT.format(python=python, core=core))
    shim.chmod(0o755)
    return shim


def main(argv: list[str]) -> int:
    real_git = os.environ.get("AUTOBUILD_REAL_GIT")
    worktree = os.environ.get("AUTOBUILD_WORKTREE")
    if not real_git or not worktree:
        print("autobuild git guard: AUTOBUILD_REAL_GIT / AUTOBUILD_WORKTREE not set; refusing", file=sys.stderr)
        return 126
    reason = check_git(argv, Path(worktree), Path.cwd(), read_only=os.environ.get("AUTOBUILD_ROLE") == "reviewer")
    if reason:
        print(f"autobuild git guard: {reason}", file=sys.stderr)
        return 126
    os.execv(real_git, [real_git, *argv])
    return 127  # unreachable


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
